### ISSUE TITLE
Different styling for the search result highlights?

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#354]
Typesense helpfully surrounds the words that are actually matched with `<mark>word</mark>`, allowing us to highlight them. Currently, we are using the default browser style, making them italic:

![image](https://user-images.githubusercontent.com/4048809/89714922-7f73c400-d991-11ea-98d2-3b21bb9c4242.png)

This may not be obvious enough. We should consider using a different style. May change the color?

**Comment by mal-tee** [comment]
I would prefer the highlights to be bold(er), but of course that is not easily possible if we want to highlight the already bold title. Do our fonts support fine-grained font-weights? Otherwise, we might be able to emulate bolder text with other styling options.

Changing the text-color is a good idea as well, but we have to be cautious to strike the right balance between visibility and good-looking. 😄

**Comment by baltpeter** [comment]
> Do our fonts support fine-grained font-weights?

Our font has tons of weights but we are currently not loading them and—to be honest—I would prefer to keep it that way. Not sure how mixing different weights like that would look, either.

**Comment by zner0L** [comment]
How about underlines?

**Comment by baltpeter** [comment]
> How about underlines?

![image](https://user-images.githubusercontent.com/4048809/89762982-156a3480-dae1-11ea-9669-38a399cbad54.png)

Not sure…

**Comment by zner0L** [comment]
<img width="1006" alt="Screen Shot 2020-08-12 at 18 30 53" src="https://user-images.githubusercontent.com/4049135/90041786-1316fe80-dcca-11ea-89b5-5c176c777070.png">
 How about dis?

**Comment by baltpeter** [comment]
I don't mind that, that's actually quite nice.

But we need to make sure that it still works when hovering over a result.

**Comment by mal-tee** [comment]
Seems like we settled on a style. Should we turn this into a regular (hacktoberfest) issue?

**Comment by Kamlesh72** [comment]
I am new to open source and this will be my first contribution.
-May I work on this during hactober fest or is it already assigned to someone else?

**Comment by mal-tee** [comment]
Go for it, I've assigned you! Happy hacking. 

Make sure to read our README which explains how to get everything started.

**Comment by Kamlesh72** [comment]
Thanks @mal-tee
Okay, I will surely check the Readme file.

**Comment by Kamlesh72** [comment]
where can I find the source files?

**Comment by zner0L** [comment]
Which source files are you referring to?

**Comment by Kamlesh72** [comment]
https://www.datarequests.org/company/

Search any company name here.
So here I want to change font style of searched word. I tried but didn't find it's file where I can edit it.

**Comment by zner0L** [comment]
Maybe start looking [here](https://github.com/datenanfragen/website/blob/527f657cdb2503e51b82b763d4c864015faef85e/assets/styles/elements.scss#L298).

**Comment by Kamlesh72** [comment]
I am getting some error in Hugo server.

**Comment by Kamlesh72** [comment]
Error building site: cannot create "de/e.v.": Windows filename restriction
Built in 104804 ms

I got this issue while following readme file and running "hugo server" command.

**Comment by baltpeter** [comment]
@Kamlesh72 I've just merged #698 which adds a section to the README with instructions on developing on Windows, which also addresses this problem.

**Comment by ThisIsFaar** [comment]
can I work on this issue?

**Comment by baltpeter** [comment]
@ThisIsFaar The issue is already assigned to @Kamlesh72. Not sure whether they are still working on it.

**Comment by Kamlesh72** [comment]
@baltpeter If possible please assign it to @ThisIsFaar. I am still getting few errors in windows.

**Comment by ThisIsFaar** [comment]
Hey, @baltpeter thank you for assigning me this issue.
how is this, is it fine?
![image](https://user-images.githubusercontent.com/67395591/136141506-7d9a260e-1e15-4758-a81d-13076fea9d94.png)

**Comment by Kamlesh72** [comment]
@baltpeter  How about using blue color underline?

**Comment by baltpeter** [comment]
We should use the style proposed by @zner0L, which we already agreed on: https://github.com/datenanfragen/website/issues/354#issuecomment-672980975

You only need to find a variant of that for when the user is hovering over an item.

**Comment by ThisIsFaar** [comment]
I have set up the project on local but when running `hugo server` cmd for starting the server, I am getting this error
![image](https://user-images.githubusercontent.com/67395591/136196413-0e7c75bd-800a-4c68-9f6d-f1c5c8355064.png)

**Comment by baltpeter** [comment]
Depends on your system: https://gohugo.io/getting-started/installing/
